version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsfeed_db
    ports:
      - "3307:3306"  # Ensure it's port 3307 on host, and port 3306 internally
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_DB=newsfeed_db
      - SECRET_KEY=a3b2c47f8bcae1234567abcd98ef1234567aa9b3cdef9b2345678aabbccddeee
      - JWT_EXPIRATION=3600
    depends_on:
      db:
        condition: service_healthy  # Wait for db to be healthy before starting app
    links:
      - db  # Link the db service to the app for hostname resolution

volumes:
  db_data: